Include last job to create pretty output

diff --git a/.github/workflows/yearly_analysis.yml b/.github/workflows/yearly_analysis.yml
--- a/.github/workflows/yearly_analysis.yml
+++ b/.github/workflows/yearly_analysis.yml
@@ -86,7 +86,7 @@ jobs: # define jobs
           path: data/Montserrat_forest_bird_monitoring_yearly_NIMBLE_model_data.RData
           retention-days: 1 # this sets the time for how long the artifact is saved under the artifact link
 
-  job_run_Nmix_model_in_NIMBLE:
+  job_run_Nmix_model:
     runs-on: macos-latest 
     needs: job_data_preparation_nimble
     strategy:
@@ -138,6 +138,50 @@ jobs: # define jobs
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           git push origin HEAD:main
+
+  job_create_plot_report: # start another job
+    runs-on: macos-latest
+    needs: job_run_Nmix_model # set dependency to first job because the output of this job is needed for the current one 
+    
+    steps:
+      - name: Checkout repository # provide a name for this step within the job
+        uses: actions/checkout@v3
+
+      - name: Set up R environment
+        uses: r-lib/actions/setup-r@v2
+
+      - name: Install R dependencies 
+        run: | 
+          Rscript -e 'install.packages(c("tidyverse", "data.table"))' 
+          Rscript -e 'filter <- dplyr::filter; select <- dplyr::select; rename <- dplyr::rename'
+
+      - name: Run general data preparation 
+        run: Rscript 'Montserrat_forest_bird_monitoring_create_summary_table_plot_report.R' # run RScript to prepare data for Nmix models in NIMBLE
+
+      - name: Configure git # this code is needed to make the created RData with all prepared data in the workflow available in the repo outside any git actions 
+        run: |
+          git config --global user.name "github-actions[bot]" 
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+
+      - name: Commit changes to git repository 
+        run: |
+          git add output/Annual_estimates2024.csv
+          git add output/Trend_estimates2024.csv
+          git add output/Montserrat_ForestBird_Trends_2024.pdf
+          git commit -m "Summary tables of annual estimates, trends and plot from Nmix calculated in git actions workflow" || echo "No changes to commit" # the echo ensures that even if there are no changes, and no commit is performed, the workflow wont fail
+
+      - name: Pull latest changes from main
+        run: |
+          git fetch origin main
+          git merge --no-edit origin/main
+          
+      - name: Push changes to the repository
+        env: 
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git push origin HEAD:main
+
+
 
           
 
