added prepared nimble data with push to repo
mapdata summary failed because data were not available in repo

diff --git a/.github/workflows/yearly_analysis.yml b/.github/workflows/yearly_analysis.yml
--- a/.github/workflows/yearly_analysis.yml
+++ b/.github/workflows/yearly_analysis.yml
@@ -75,7 +75,28 @@ jobs: # define jobs
 
       - name: Run general data preparation
         run: Rscript 'Montserrat_forest_bird_monitoring_data_prep_Nmix_model_def_nimble.R' # run RScript to prepare data for Nmix models in NIMBLE
+        
+      - name: Configure git # this code is needed to make the created RData with all prepared data in the workflow available in the repo outside any git actions
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
 
+      - name: Commit changes to git repository
+        run: |
+          git add data/Montserrat_forest_bird_monitoring_yearly_NIMBLE_model_data.RData
+          git commit -m "Automatically prepared NIMBLE input data" || echo "No changes to commit" # the echo ensures that even if there are no changes, and no commit is performed, the workflow wont fail
+
+      - name: Pull latest changes from main
+        run: |
+          git fetch origin main
+          git merge --no-edit origin/main
+
+      - name: Push changes to the repository
+        env:
+          GITHUB_TOKEN: ${{ secrets.PAT_Montserrat }}
+        run: |
+          git push origin HEAD:main --force
+          
       - name: Pass prepared data and defined model to next job # using artifacts
         uses: actions/upload-artifact@v4
         with:
@@ -194,7 +215,7 @@ jobs: # define jobs
         run: |
           git add output/Annual_estimates.csv # this will overwrite the outputs every year!
           git add output/Trend_estimates.csv
-          # git add output/Annual_estimates_mapdata.csv
+          git add output/Annual_estimates_mapdata.csv
           git add output/Montserrat_ForestBird_Trends${YEAR}.pdf # ERROR: if envYEAR != lastMonitoringYEAR -> ERROR this will lead to a library of annual reports and trend plots for every year
           git add output/Montserrat_ForestBird_AnnualReport_${YEAR}.html
           git commit -m "Summary tables of annual estimates, trends and plot from Nmix calculated in git actions workflow" || echo "No changes to commit" # the echo ensures that even if there are no changes, and no commit is performed, the workflow wont fail
