Update yearly_analysis.yml
try to resolve issues with homebrew

diff --git a/.github/workflows/yearly_analysis.yml b/.github/workflows/yearly_analysis.yml
--- a/.github/workflows/yearly_analysis.yml
+++ b/.github/workflows/yearly_analysis.yml
@@ -27,11 +27,11 @@ jobs: # define jobs
 
           Rscript -e 'filter <- dplyr::filter; select <- dplyr::select; rename <- dplyr::rename'
 
-      - name: Install pkg-config and pkgconf silently # this is solely a step to overcome issues with lots of annoying but non fatal and distractive error messages
-        run: |
-          brew install pkg-config || true
-          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
-          brew install pkgconf || true
+      # - name: Install pkg-config and pkgconf silently # this is solely a step to overcome issues with lots of annoying but non fatal and distractive error messages
+      #   run: |
+      #     brew install pkg-config || true
+      #     export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
+      #     brew install pkgconf || true
 
       - name: Run data preparation for Nmix models in NIMBLE
         run: Rscript 'Montserrat_forest_bird_monitoring_data_prep.R'
